### ISSUE TITLE
Multi geth link broken

### ISSUE THREAD

**Issue by malefol7** [ethpool-update-project/open-callisto-pool#4]
hi, the link to multi geth does not seem to be working, please correct.
https://github.com/ethereumsocial/multi-geth/releases/download/v1.8.10/multi-geth-linux-v1.8.10.zip

Pools: https://cominers.org

**Comment by phatblinkie** [comment]
yes, the readme fast becomes out dates. you dont need to use multi geth, use which ever geth client is written for your coin you want to support.
you can find more updated info on this too from 
https://github.com/phatblinkie/official-pirl-testnet-pool

**Comment by phatblinkie** [comment]
removed the multigeth stuff, actually all the geth stuff off readme.  closing issue
