### ISSUE TITLE
Block Reward Amount is Still 420CLO

### ISSUE THREAD

**Issue by ZAX6** [ethpool-update-project/open-callisto-pool#5]
Hi guys
as you know the CLO block reward is now 360 I guess but the pool server sticks to 420. and the effect is that the payout would crash because of insufficient balance.
anyone got a solution for this problem ,
i have update the go-callisto node and nothing has happend

#### System information
Geth version: go-callisto
Redis version: `redis-server --version`
OS & Version: Ubuntu

**Comment by mathias7799** [comment]
Change the block reward in https://github.com/ethpool-update-project/open-callisto-pool/blob/master/payouts/unlocker.go

**Comment by phatblinkie** [comment]
you have to recompile it after the change too, and then restart the binary

**Comment by pool2mine** [comment]
Sorry to change the subject but i didn't wanted to open a new issue... can i use this pool for ethereum? i installed open-ethereum-pool but i'm having some issues with worker stats and i see this one is an updated version. please let me know. Thanks!

**Comment by mathias7799** [comment]
You can, with some edits to the unlocker.go and environment.js
