### ISSUE TITLE
Site Hash Chart

### ISSUE THREAD

**Issue by pool2mine** [ethpool-update-project/open-callisto-pool#6]
hi, i was taking a look at this pool but seems a little more complex than the regular open-ethereum-pool, i saw a lot of configs depending on the hash rate, and many other things that i will not use, i have a simple ethereum pool but i liked very much the site chart. Is it possible to use that chart on the sammy007 pool version? please let me know. Thanks!

**Comment by kirill190497** [comment]
also interested in this question

**Comment by pool2mine** [comment]
I was able to run sammy007 pool and a separate config only to run the api for this pool so i am only using the frontend, everything works fine except for the chart. The chart is not working. Anyone with this issue? Any solution?

**Comment by phatblinkie** [comment]
There is custom code I the api section that is compiled into the binarybthat makes the charts work. You can’t just throw the front end on on Sammy binaries it and make it work

**Comment by pool2mine** [comment]
Thanks, i will try to install this one from scratch

**Comment by pool2mine** [comment]
ok, here is what i did...
I installed the pool, build the site, fixed the dependency problem caused by the intl-format-cache folder (not a problem of the pool, but ember problem)
I used api.json on configs folder and only changed: threads to 12 cores, coin  to "eth".
i connected a miner just to test the site but still nothing on the chart

then i changed hashratewindow and hashratelargewindow to lower times just to have stats quicker but results were the same
here are screenshots showing hashrate but the chart seems not to be responding.

any idea would be really appreciated. thanks!!
![Screenshot 2019-09-22 21 13 42](https://user-images.githubusercontent.com/38216354/65397440-29e4f780-dd7e-11e9-800b-ce6af0cef7a0.png)
![Screenshot 2019-09-22 21 13 53](https://user-images.githubusercontent.com/38216354/65397441-2a7d8e00-dd7e-11e9-81df-1cc9314f5d29.png)

**Comment by phatblinkie** [comment]
I think start all with the new binary, the api, stratum, unlocker, etc

**Comment by pool2mine** [comment]
Ok, yes, that’s exactly what i did... only that before “make all” i modified unlocker to show correct reward for eth, but this time i didn’t use any of the sammy files

**Comment by pool2mine** [comment]
I was thinking maybe the chart is only working for CLO and not ETH... Did someone got it working on ETH? please let me know. thanks!

**Comment by pool2mine** [comment]
@phatblinkie quick question... does it matter where do i install the pool? because i installed it in /var/www/open-callisto-pool and that's the only thing i did different from the readme... i made a clean install and same... everything works good except for the chart. sorry to bother, just trying to figure this out.

**Comment by phatblinkie** [comment]
no it does not matter where the data for the website is stored. it works like this, 
you compile the code, it makes the open-ethpool binary (the one that reads the json files)

you start that, it has to be that one, not the open eth pool or sammy, or some other flavor.

this binary has hooks built in, that makes the stats tables in the redis database. if you do NOT use this binary, then those tables will not be created or updated.

the website has js code that will look at the (yoursite.com)/api/stats url to get the data for the charts. if your charts are not working, either your not running the correct binary.

you cannot, run the stratums of another binary, and expect the website to be able to draw a graph.  and yes, it would work for any ethash based coin, eth, pirl, clo, etc, moac, etc.

**Comment by phatblinkie** [comment]
you can ping me pirl discord and i can take a look at what you did to help

**Comment by pool2mine** [comment]
Thank you very much, i can't find your discord user, mine is AnthonyT#4061

**Comment by pool2mine** [comment]
hi @phatblinkie  I installed it again... the only thing i did different this time is started serviced as the readme said, but same result... here's what i did

i have geth installed, not parity (i don't think this is the issue as the rest is working fine)

git clone this repository
change unlocker to show the correct reward
make all
changed environment.js to my address, correct reward and my coin (eth)
cd www
sudo npm install -g ember-cli@2.9.1
sudo npm install -g bower
npm install
bower install

I manually copied the dependency files inside /node_modules/intl-format-cache (this is a work around for the missing files when you install npm, an error that started earlier this year)

and then ./build

then, i only changed all json's coin (eth where clo was)

and started all services

the pool works perfect, i connect a miner and everything works but not the chart. it looks like it's off, i took a look on other testpools that has 0 hash and even if there is no hash you have a new dot each 20min, in my site there is only one dot and never changes.

my testpool is installed on a domain that i have for tests only tormaca.com if you want to take a look, it's untouched, i only changed what i mentioned before.
![Screenshot 2019-10-07 21 50 22](https://user-images.githubusercontent.com/38216354/66361689-a4507280-e94d-11e9-816a-87e5e56cf308.png)

**Comment by phatblinkie** [comment]
see the difference in the stats pages api json data
https://pirl.cryptopools.info/api/stats
vs
http://tormaca.com/api/stats

i would need to ssh in to see what the problem really is here. i suspect your fix for the modules may have also broken them

**Comment by pool2mine** [comment]
thanks! can you add me on discord or telegram (@pool2mine) so i can give you the details? the fix i told you before is because front end wasn't displaying, just background and footer, in the "lib" and "src" folders inside node_modules/intl-format-cache i only added a few files, but didn't replace or delete anything.

**Comment by phatblinkie** [comment]
i hate telegram, join this https://discord.gg/4jR2Km
then you will find me that is the pirl.io discord

**Comment by phatblinkie** [comment]
we found the issue, the cron library used, no longer accepts the seconds field, (which was non-standard)
change the api section from 

    "poolCharts":0 "*/20 * * * *",
    "poolChartsNum":74,
    "minerCharts":"0 */20 * * * *",

to

    "poolCharts":"*/20 * * * *",
    "poolChartsNum":74,
    "minerCharts":"*/20 * * * *",

**Comment by pool2mine** [comment]
thanks @phatblinkie closing the issue now!

**Comment by Miguel974** [comment]
> ok, voici ce que j'ai fait ... J'ai installé le pool, construit le site, corrigé le problème de dépendance causé par le dossier intl-format-cache (pas un problème de pool, mais un problème de braise) J'ai utilisé api.json sur dossier configs et seulement changé: threads à 12 cœurs, coin à "eth". j'ai connecté un mineur juste pour tester le site mais toujours rien sur la carte
> 
> puis j'ai changé hashratewindow et hashratelargewindow pour réduire les temps juste pour avoir des statistiques plus rapides mais les résultats étaient les mêmes ici sont des captures d'écran montrant le hashrate mais le graphique ne semble pas répondre.
> 
> toute idée serait vraiment appréciée. merci!! ![Capture d'écran 2019-09-22 21 13 42](https://user-images.githubusercontent.com/38216354/65397440-29e4f780-dd7e-11e9-800b-ce6af0cef7a0.png) ![Capture d'écran 2019-09-22 21 13 53](https://user-images.githubusercontent.com/38216354/65397441-2a7d8e00-dd7e-11e9-81df-1cc9314f5d29.png)

Hello as you have fixed the dependency issue caused by the intl-format-cache folder

**Comment by Miguel974** [comment]
How

**Comment by phatblinkie** [comment]
are you going to use this for eth or another eth clone? i have a better pool if so

**Comment by phatblinkie** [comment]
use this one, it has the original looking ethpool and the callisto nicer looking one too, with a lot more updates
https://github.com/ethpool-update-project/open-ethereum-pool
